Throw relevant exception in tests
If the channel cannot be created, the tests throw
Fatal error: Call to a member function exchange_delete() on a non-object
instead of relevant exception